"""
Stage 0 - Landing: the synthetic operator's source systems drop one business date's files.

  erp         EAM asset register (mysqldump day 1, then CDC JSON lines), work orders (PSV + trailer)
  inspection  ~30 inspection reports a day (PDF; ~20 % image-only scans; one corrupt)
  drone       4 drone flights a day (Motion-JPEG AVI + sidecar JSON)
  drawings    20 P&ID sheets day 1 (PDF + PNG), revisions later
  seismic     2 SEG-Y 2D lines day 1, one re-sent on day 2
  welllogs    12 LAS 2.0 well logs day 1, a re-log later

Every <landing>/<source>/<date>/ folder gets _manifest.json (file, size, sha256, counts as the
source reports them). Generated by generators/ from one seeded asset universe; planted faults
in generators/faults.py. Sensor telemetry is not landed here: it streams through Kafka
(stream/producer/sensor_producer.py).

Usage:
  spark-submit land_sources.py --business-date 2026-10-04 [--landing URI]
  python cde/jobs/land_sources.py --all-dates --landing data/landing      # laptop, no Spark
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ogx_common as C  # noqa: E402

from generators.land import batch  # noqa: E402


def parser():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--business-date", type=C.parse_date)
    p.add_argument("--all-dates", action="store_true")
    p.add_argument("--landing", default=C.DEFAULT_LANDING)
    p.add_argument("--sources", default="", help="comma-separated subset of sources")
    p.add_argument("--db-prefix", default=C.DEFAULT_PREFIX)
    p.add_argument("--pipeline-run", default=None)
    return p


def land(fs, landing: str, business_date, sources=None) -> dict:
    out = {}
    for source, files in batch(business_date, sources).items():
        folder = f"{landing}/{source}/{business_date.isoformat()}"
        fs.delete(folder)
        for name, data in files:
            fs.write_bytes(f"{folder}/{name}", data)
        out[source] = (len(files) - 1, sum(len(b) for n, b in files if n != "_manifest.json"))
        print(f"  {source:<10} {out[source][0]:>3} files {out[source][1] / 1e6:7.2f} MB -> {folder}", flush=True)
    return out


def main(argv=None, spark=None) -> int:
    args, _ = parser().parse_known_args(argv)
    landing = args.landing.rstrip("/")
    if "://" not in landing:
        landing = str(Path(landing).resolve())
    if spark is None and not landing.startswith(("/", "file:")):
        spark = C.get_spark("ogx-land-sources")
    fs = C.filesystem(spark, landing)
    dates = [C.parse_date(d) for d in C.CFG["business_dates"]] if args.all_dates else [args.business_date]
    sources = [s for s in args.sources.split(",") if s] or None
    for d in dates:
        print(f"landing {d}", flush=True)
        land(fs, landing, d, sources)
    return 0


if __name__ == "__main__":
    sys.exit(main())
